### PR TITLE
feat: add feature for check admin role to acess admin page (client side)

### PR DESCRIPTION
**Pull request by Ouliang-99**
please review my code !

### CODE REVIEW

**Review by dustybun97 — APPROVED** [review]
The features work well. 👍

**Comment by jaiisymnz** [comment]
reviewed, pass

**Comment by TheYami** [comment]
that great

**Comment by Chanathip-Khw** [comment]
pass

**Review by TheYami — APPROVED** [review]

**Review by jaiisymnz — APPROVED** [review]

**Pull request merged**
